### ISSUE TITLE
Allow insistent notifications to be set individually for end of work / end of break

### ISSUE THREAD

**Issue by BradSteffen** [goodtime-productivity/Goodtime#121]
Hi there:
Thank you for making a great tool!

Would it be possible in a future release to be able to toggle insistent notification individually for the End of Work notification and End of Break notification?

Use case:  End of break notifications need to be more annoying (especially for teen students) but End of Work notifications need to be easily ignored in case of good flow.

Thank you again,

- Brad

**Comment by adrcotfas** [comment]
Hi Brad,
You could create a custom build to include this feature if you want.
I'll consider it but I wouldn't like to bloat the app with too many features. The settings page is already quite large at the moment.

Cheers,
Adrian
