### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mdmk** [goodtime-productivity/Goodtime#122]
I started to work on the french translation.
I'm roughly halfway through.
A user already completed the translation at 100%, but apparently he picked bot suggestions and the results are sometimes very poor.
Is there anything to do for my translation to be validated?
Are the latest strings always pushed in the latest builds or is there any kind of validation on your part?
Thanks.

**Comment by mdmk** [comment]
On a side note, I spotted a string that is not localized.
Menu > Open Source Licences > 'Licenses' should be translated.
I can attach you a screenshot if needed. 
Should I open a separate issue for this?

**Comment by adrcotfas** [comment]
Thanks!
I'll take the strings from crowdin and update the app.
I'll fix the Licences string too.

**Comment by mdmk** [comment]
@adrcotfas 
I spotted another string that is not localized.
Menu > About > 'About' should be translated.
