### ISSUE TITLE
Early session finish 

### ISSUE THREAD

**Issue by MrCryoPain** [goodtime-productivity/Goodtime#123]
A further option would be preferable to finish/stop a session - How about a long press on the current timer followed by a pop-up, to accept or deny the session abroad.

**Comment by MrCryoPain** [comment]
Right now the longpress redirects to the options menu, hiding the options under the three bar options button seems fine to me, since it's common android practice.

**Comment by adrcotfas** [comment]
Did the tutorial snackbars appear for you when you first started the app?
Swipe gestures on the timer will control it. Swipe down to stop. Left or right to skip the current session and up to add one more minute.

**Comment by MrCryoPain** [comment]
Ok, I did first open it quite a while ago. So I can not remember if it appeared, if it's implemented then they propably did. 
So far that solves the issue for me, nice concept with the swipes. Maybe a timer control readme in the menu somewhere could be interesting for occurences like these.
