### ISSUE TITLE
Add a simple indicator that shows completed sessions over needed sessions for a long break

### ISSUE THREAD

**Issue by isamert** [goodtime-productivity/Goodtime#126]
Title may not be clear, let me explain:
- Say that I'm on third session session and I need one more session to have a long break
- The indicator shows `3/4`.

And it would be nice to have the ability to reset this counter on click like that it simply sets current counter to `0/4` (without removing any daily done sessions).

It would be really helpful to have this feature. Thanks for your great work!

**Comment by adrcotfas** [comment]
I don't have any plans to include such an indicator but you could make use of adding extra minutes if you need more time or even better, swipe to one of the sides to skip the current session until you reach the long break when you need it.
