### ISSUE TITLE
Timer freezes at 01 second left

### ISSUE THREAD

**Issue by ardydo** [goodtime-productivity/Goodtime#127]
I'm on Android 7.0, without any modifications on a Moto C.

The clocks runs fine but the work section never actually ends. The timer just stops at 01 second left, wheter the screen is on or off or the app is open. The app is not frozen since it keep responding to other actions and whenever I can manually end the session and it registers just fine and then play the notification that the timer is up.

I'm not sure if this is the default behavior because I can't really remember the instructions from when I first used the app (the ones that tell me what swiping in each direction does) and I couldn't find a way to replay it or if it is an issue with the app or my own phone, since I don't have another one to test it on, so I'm opening an issue.

I've tried searching for another one and nothing showed up, which may suggest that this is either an issue with my phone or something particular.

**Comment by adrcotfas** [comment]
Sounds like an issue on your phone. Does it happen all the time?
When the timer reaches 0, it should reset to the current session duration and a notification and dialog will pop-up.
For you, the notification plays after you swipe down to manually stop the timer?
Did you disable battery optimization for this app? You'll find a shortcut for this in the settings. The battery optimization usually breaks or delays the alarm.

**Comment by ardydo** [comment]
Yeah, it happens every time and I did disable the battery optimization for
the app. When I swipe the notification pops up no problem.

I suspect that the battery optimizer os just ignoring my settings because
there are other things breaking that are supposed to get fixed by disabling
the optimization but that just wont work (my status bar clock just stop
updating, for example). So I’ll try exploring in that direction.

Thanks for your help and time :)

**Comment by EmVee381** [comment]
same issue on Realme 8, Adndroid 12, battery optimisations disabled. it does not notify until i open app screen, then i see 00:00 on timer, i need to touch it as pause, it starts blinking, then i touch again as resume and it takes another 1-2 sec until session finished popup appears with alarm. In this sense it is unusable :(

**Comment by EmVee381** [comment]
I tried again today, and the issue persists. The alarm stops at 00:00, and I receive no notification. I'm using the latest Android 13 on my device. By the way, your app is the only one among those I've tried where notifications don't work.

**Comment by EmVee381** [comment]
hmm so i found it is related to interval set to just 1 minute... so maybe you should fix it or make settings slider minimum from time greater then 1  :)
