### ISSUE TITLE
Remarks on text in UI

### ISSUE THREAD

**Issue by mdmk** [goodtime-productivity/Goodtime#128]
I open this issue to gather some more untranslated strings (following #122 now closed) and formulate some remarks on text in UI.

Non localized strings :

- Menu > Open Source Licences > `Licenses` (as seen in #122)
- Menu > About > `About`
- In intro, `Back` and `Next` buttons tooltip on long press

Inconstistancies: 

- In French, `Upgrade` translates to "Mise à niveau" or "Mettre à niveau" (Upgrade can be a word or a verb respectively). I did not touch your translation of "Version Premium" but it is not litterally equivalent.
Perhaps the english string would also benefit from being more explicit as `Premium Version`?
- Menu > Statistics > Select label > `all` --> Should be All with caps
- Date format in statistics does not adapt to language
- I assume `Insistent notification` is not the same as Persistant notification.
Insistant repeat, while persistant stay forever without repeating.
I think a notification cannot be insistant, as a thing, it does not have will of its own.
Something more impersonal would be better, like 'Repeat notification until aknowledged' or a better formulation.
- `Moves the timer while the screen is on` : I don't understand what this feature does. The timer goes on if screensaver on, Only if this feature is turned on? For me it is unclear what this option does with this formulation.

**Comment by mdmk** [comment]
I also finished french translation.
I reviewed and upvoted all the strings I did not touch.
I'll make a second proofreading when integrated in a future build.

**Comment by adrcotfas** [comment]
You can test the full version from F-Droid to see how `Moves the timer while the screen is on` behaves.
This feature works together with "Keep the screen on" and when enabled, moves the timer position every minute to avoid screen burn.

**Comment by mdmk** [comment]
I tested both standard Google Play and F-Droid version.
But I did not wait 60 seconds, my bad.
Now I understand thanks.
I suggest changing the explanation text to something like : Moves the timer every minute while the screen is on to avoid screen burn.
Just to be sur every user who activate the first tick is aware of screen burn risk and that option is a possible mitigation.

**Comment by mdmk** [comment]
And that also clarifies that the effect is visible every 60 seconds.

**Comment by adrcotfas** [comment]
I think this is already clarified in the word "Screensaver".

**Comment by mdmk** [comment]
I understand the original function of screensavers is in fact to preserve screen.
But it is almost useless on modern LCD where burning is not  frequent and not permanent and in this case the purpose is more entertainment than anything else.
Or practicality of always-on scren with energy efficient oled display, that are more prone to burning on the other side.
I think most, non technical users will use screensaver without knowing about burn-in.
Perhaps the best would be to tick the "Move" option by default?
And not bother with formulation, as safeguard mesure is taken by default.
