### ISSUE TITLE
Adding multiple tags

### ISSUE THREAD

**Issue by mx-psi** [goodtime-productivity/Goodtime#129]
The current version does not support a task to have multiple tags. I would personally find it useful if more than one tag was allowed for each task, so that I can more precisely categorize what I was doing.

Alternatively, a task description field would also do the trick.

**Comment by adrcotfas** [comment]
Unfortunately, I don't have any plans to implement multiple tags anytime soon. If someone ever wants to implement this, please keep in mind the backwards compatibility with the current statistics stored in the database.
A design problem that I see is the timer color according to the current label.
