### ISSUE TITLE
Notification to early [Version 2.0.6]

### ISSUE THREAD

**Issue by CendonArc** [goodtime-productivity/Goodtime#131]
When the timer is running in the background the app often notifies me that the session is over before the timer was at 0 seconds, on average there was around a minute left. If I then answer the prompt to start the break/session, two timers are running parallely. The display then switches rapidly between the timers every second they update.
If I choose Close on the prompt, the original timer will run to 00 and stay at that number without notifying me that the session/break has finished.
The notification in the panel stays unresponsive until the old timer has ended and the new timer takes over.
Sometimes this messes up the statistics as well and counts a session double, but I haven't found out when exactly that happens yet.
I'm using a Huawei P20 lite with power saving mode running, but with goodtime excluded in the settings.
My Goodtime install is from Fdroid.

**Comment by adrcotfas** [comment]
I'll provide a fix for the multiple timers bug but this will not fix the alarm accuracy which is affected by OEM specific implementation. Do you get the same behavior with power saving off?

**Comment by adrcotfas** [comment]
This was fixed in 2.0.8.
