### ISSUE TITLE
The latest release is Goodtime v2.0.8 but its apk asset is 2.0.6

### ISSUE THREAD

**Issue by realrufans** [goodtime-productivity/Goodtime#133]
The latest release is Goodtime v2.0.8 but its apk asset is 2.0.6

Kindly check if this is right .
![Screenshot_20190330-102340.png](https://cdn.steemitimages.com/DQmcHTBeKPTpV3LWnhUc4KyGdGa1wMPQkeaN8Hk7hnN6f2T/Screenshot_20190330-102340.png)

**Comment by adrcotfas** [comment]
The name of the apk is wrong but the version is 2.0.8. It's a copy paste error.
