### ISSUE TITLE
App isn't Installing after downloading the apk from the release Page

### ISSUE THREAD

**Issue by realrufans** [goodtime-productivity/Goodtime#134]
## Expected behavior

To successfully install the raw apk file

## Actual behavior
 It gives ``` app not installed``` error message while installing it.

## How to reproduce
Go to [Goodtime v2.0.8 ](https://github.com/goodtime-productivity/Goodtime/releases/tag/2.0.8) release Page.
* Then download and install goodtime_2.0.8.apk from the page.

## Devices
Device: Tecno Camon Xpro , L8+
OS: Android
Version 8.1, 5.1

https://github.com/goodtime-productivity/Goodtime/releases/download/2.0.8/goodtime_2.0.8.apk

**Comment by realrufans** [comment]
## Gif ![80qwf7edy6.gif](https://img.esteem.ws/80qwf7edy6.gif)

**Comment by adrcotfas** [comment]
Does 2.0.6. or any other apk from the Releases page work for you?

**Comment by realrufans** [comment]
I downloaded the whole six releases;

- Goodtime v2.0.8 didn't install
- Goodtime v2.0.6 didn't install
- version v2.04 didn't install
- Goodtime v2.0.3 didn't install
- [Goodtime v2.0](https://github.com/goodtime-productivity/Goodtime/releases/tag/v2.0) (finial release) didn't install
- [Goodtime v1.2.0](https://github.com/goodtime-productivity/Goodtime/releases/tag/V1.2.0) ( first release) installed
- Goodtime v1.1.0 Installed

**Comment by adrcotfas** [comment]
Thanks for the feedback! I suggest you take the apk from F-Droid until I fix the ones from here.

**Comment by realrufans** [comment]
Okay 👍
