### ISSUE TITLE
Productive time in statistics should include break

### ISSUE THREAD

**Issue by ema-pe** [goodtime-productivity/Goodtime#136]
Hi!

I use your application every day, but I found a "problem". The app register only the productive time of a session in the statistics, but also the break time should be included, because it is important. A session is indeed work plus break.

So, with a session of 25 minutes of work and 5 of break, for example, the app should register 30 minutes of productive time, and only optionally specify the effective work time.

**Comment by adrcotfas** [comment]
Hi,
That's the whole point of the app, to measure the actual working time. The breaks should not be part of the statistics. You can't measure the breaks accurately if someone doesn't resume a session immediately after a break, for example.
There would be no difference between a W25/B5 and W5/B25 using your idea.

**Comment by ema-pe** [comment]
Ok, I understood your clarification, actually you've right.
