### ISSUE TITLE
Merge stopping and skipping a session

### ISSUE THREAD

**Issue by nemuc** [goodtime-productivity/Goodtime#137]
Currently these swipe gestures on the timer will control it:
1.  Down to stop.
2. Left or right to skip the current session.
3. Up to add one more minute.

To me, skipping and stopping the session is basically the same. Thus, I propose to get rid of the skipping option and give the stopping session a more descriptive name such as "Finishing current session".

**Comment by adrcotfas** [comment]
For custom builds, go ahead and fork it and modify it to your needs.
I don't have any plans on removing the "skip" functionality.
