### ISSUE TITLE
Enhancement: Icons for Swipe gestures

### ISSUE THREAD

**Issue by nemuc** [goodtime-productivity/Goodtime#138]
Currently these swipe gestures on the timer will control it:
1. Down to stop.
2. Left or right to skip the current session.
3. Up to add one more minute.

In order to make it more intuitive, I propose to add little Icons:
- for adding one more minute, I propose this icon: "+1"
- for stopping the session, I propose a little flag like at the end of a race.

**Comment by adrcotfas** [comment]
I imagine that you propose buttons instead of swipe gestures. I don't have any plans on removing the swipe gestures and adding buttons instead.

**Comment by nhfo** [comment]
Gestures need not be replaced with buttons, instead there could be just icons to hint what swipe in that direction would do, something like camera icon on the lock screen, one can swipe from it to start camera, it is not a button. In our use case, icon can even be passive and show no animation whatsoever.

**Comment by adrcotfas** [comment]
This is planned and will come in the future or sooner if someone wants to contribute.

**Comment by adrcotfas** [comment]
I wasn't able to make it pretty with icons and improved the tutorial instead #144.
It is now possible to restart the tutorial from the About page.
