### ISSUE TITLE
Simplify label selection

### ISSUE THREAD

**Issue by nemuc** [goodtime-productivity/Goodtime#139]
The current way to select a label is:
1. Select a label.
2. Pressing `OK` to confirm. 

My proposed way to select a label is:
1. Select a label and the choice is automatically saved. The `OK` and `Cancel` buttons can then be removed.

Reasoning:
With the proposed method, the user needs to do one click less. Also, there is no longer the issues that users select a label but don't see that they still have to confirm the choice and thus have wrong statistics.

**Comment by adrcotfas** [comment]
In the Select Label dialog, there's also a button for "Edit labels" which will looks better as a neutral button in this group of 3 along with OK and Cancel.
The ChipGroup from the Select Label dialog acts like a "at most one item selected" group. That means that you don't necessarily need to have a label selected. Using your proposal will mean adding another Chip for "unlabeled" sessions and I don't plan to implement it like that.
