### ISSUE TITLE
Easier switching between profiles 25/5 and 52/17

### ISSUE THREAD

**Issue by VaclavPavek** [goodtime-productivity/Goodtime#141]
Thanks for making Goodtime,

Please add an option to easily switch between profiles. Ideally under "3 dots" where a label is assigned. Or solve it more easily without having to go into settings.

Thanks for the great app

**Comment by adrcotfas** [comment]
Thanks for using the app!
This is a good idea. I thinks that a bottom or side dialog is a good option for this.

**Comment by adrcotfas** [comment]
Thanks for using the app!
This is a good idea. I thinks that a bottom or side dialog would be a good option for this.

**Comment by VaclavPavek** [comment]
I use 25/5 by default, but sometimes I need more time (programming / refactoring a larger whole) and 52/17. I usually combine profiles.
