### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by HarryHeights** [goodtime-productivity/Goodtime#143]
A privacy policy is invaluable for this kind of project. You seem not to have one. I could help create one for you. If you mind.

 @HarryHeights

**Comment by adrcotfas** [comment]
Thanks for your assistance!
But do you think it would make sense for this project? The app does not process any user data.

**Comment by HarryHeights** [comment]
Well, Privacy Policies are not created only for cases where user data is processed. The document also contains some components of the app, like; permissions, app capabilities, third-party libraries etc.

**Comment by HarryHeights** [comment]
Oh okay @adrcotfas.

**Comment by adrcotfas** [comment]
If it's fine for you, I'll close this issue.

**Comment by HarryHeights** [comment]
Sure.
