### ISSUE TITLE
Feature request: Continue work session untill user take action

### ISSUE THREAD

**Issue by nhfo** [goodtime-productivity/Goodtime#148]
I usually do not like to break my flow and start a break time when work session. It usually takes few minutes but may also take longer sometimes. I propose adding following feature to give more accurate stats.

With both "Auto start break" and "Auto start work" unselected in settings, when work session ends, a dialog with two buttons appears. User can select either to "close" or "start break". 

Another option should be added to settings, 'Auto extend work session". If selected, a work session when reaching its time limit would show dialog as in previous paragraph but instead of ending, it will keep on counting. If user chooses "close", dialog would disappear and session would keep on counting (maybe with '+' prefix). If user chooses "start break" then session would as usual but of course would realise standard session length + extra time counted.

**Comment by Samyak039** [comment]
yeah and you can even implement "add five minutes" so that if you are near to crack something you won't be annoyed by the question "Want to take a break or stop the counter?", either of them are not productive.

An option should be added either to **continue** or **extend** the current work time.

**Comment by adrcotfas** [comment]
I think I'll go for #150 as an alternative to this. What do you think?
Notifying the user just before the session ends gives him the opportunity to extend the session as he desires.

**Comment by nhfo** [comment]
> Notifying the user just before the session ends gives him the opportunity to extend the session as he desires.

True. However it forces user to react, breaking the flow. I would rather prefer if notification would repeat at some configurable interval, while session continue to extend. This way user would not be compelled to break flow but would still  not end up working very long.

**Comment by adrcotfas** [comment]
@nhfo: Thank you for your feedback but unfortunately this would imply some not so straightforward changes and will not come anytime soon.
