### ISSUE TITLE
Sound when starting a Pomodoro

### ISSUE THREAD

**Issue by sojusnik** [goodtime-productivity/Goodtime#149]
Would be great to have an additional indicator, in this case a sound, that a Pomodoro has started.

**Comment by adrcotfas** [comment]
I can't understand why this would be useful and unfortunately it would imply some not so nice logic changes.

**Comment by sojusnik** [comment]
This is especially useful when you don't see the display, but want to know if a pomodoro has started, for instance after a break or when the pomodoro was started remotely, either by [Automate](https://github.com/goodtime-productivity/Goodtime/issues/151) or another similar app.
