### ISSUE TITLE
paypal link

### ISSUE THREAD

**Issue by leela52452** [goodtime-productivity/Goodtime#153]
please change your paypal link to user friendly & easy to remember

example `paypal.me/urname`

**Comment by adrcotfas** [comment]
I appreciate your intention to donate.
You can use any of the following:
- the yellow donate button from: https://github.com/goodtime-productivity/Goodtime
- the embedded menu item from the F-Droid version
- [paypal.me/adrcotfas](https://www.paypal.me/adrcotfas)

Thanks!
