### ISSUE TITLE
Feature request: remove minute from current timer

### ISSUE THREAD

**Issue by axelsimon** [goodtime-productivity/Goodtime#157]
Sometimes, i'll start a work session and only realise i forgot to start the timer, or failed to properly start the timer, after a few minutes.

It would be helpful to be able to start the timer, and then swipe a few times to decrease the number of minutes left, to get the timer more or less to where it should have been, if it had been started on time.

Have you considered such an option?
Thanks!

**Comment by adrcotfas** [comment]
Not really. I would prefer not to add too much super specific features to the app and I cannot think of a good UX for this considering the current swipe options.
But this can be achieved by manually adding a work session in the statistics.
