### ISSUE TITLE
profiles with same name as built-in ones cannot be deleted

### ISSUE THREAD

**Issue by zanona** [goodtime-productivity/Goodtime#159]
I have accidentally created a profile with the same name of one of the built-ins (25/5) which cannot be deleted (not showing the trash icon close to it)

<img src=https://user-images.githubusercontent.com/32017/67486685-c0058980-f66c-11e9-90ab-ef9f263b4873.png width=300>

So ideally I believe it would be nice to prevent 2 things here:
1. Create profiles with same name
2. Allow deleting profiles that have the same name as built-in ones.

Thanks ;)

**Comment by adrcotfas** [comment]
That's a bug 👍 
Thanks!
