### ISSUE TITLE
an option to extend the current timer

### ISSUE THREAD

**Issue by Samyak039** [goodtime-productivity/Goodtime#161]
Some times I am working on a task and it is about to finish, I just need 2 more minutes, But then the timer goes off and I am left with two options either to take a break or start another session of 25 minutes. Both are inappropriate for that particular situation.

So it would be great if you make a new option when a timer ends to extend by 2 (or n) minutes. 
That would be great, and thanks in advanced for such a clean and amazing pomodoro app.

**Comment by adrcotfas** [comment]
I'll implement an alternative for this with #150 so one can extend the timer manually as much as he desires.
