### ISSUE TITLE
Request: Clarification of labels and preview of premium features

### ISSUE THREAD

**Issue by ninaarens** [goodtime-productivity/Goodtime#163]
In the premium features listing, it says "coloured labels". I interpreted this as labels being a basic feature, and colours for the labels being a premium feature. From testing the app, I cannot add labels at all. I suggest a clarification that labels as a whole are a premium feature unless this is a bug.

It would also be nice to get a preview of the premium features somehow. Perhaps a trial option for X number of days, more screenshots that cover everything, or expand the current informational video on the Play store. Nothing really explains what a "timer style" is, what theme colours we can expect, how an insistent notification works or what the screensaver mode will look like. This is a shame because this is a very affordable app but I like to know what I am getting before I put my money down.

**Comment by adrcotfas** [comment]
It's not a bug. The labels are not included in the basic version from Google Play. I'll consider making these things more clear in the future.
There's a set of screenshots and video on Google Play which show these labels and the timer style.
For the themes, it is indeed a bit misleading..

You can get it from F-Droid with all features unlocked with no need to pay through Google. 
If it really brings value to you, there's a donate button in the F-Droid version :).
