### ISSUE TITLE
Allow 50/10, 45/15, 52/17 and/or 45/10 as defaults

### ISSUE THREAD

**Issue by DonaldTsang** [goodtime-productivity/Goodtime#166]
Since the common pomodoro 25/5 is not completely suitable for everyone, is it possible to add these other timeboxing "standards" into the app?
- 50/10 (preferred)
  - https://www.softwaremeadows.com/posts/the_50-10_time_box_revising_pomodoro_for_software_development/
  - https://programmingzen.com/getting-stuff-done-with-the-pomodoro-technique/
- 45/15 https://www.lesswrong.com/posts/c3SKeDSycHTkmuvyR/pomodoro-for-programmers
- 52/17 (for reference) https://dzone.com/articles/the-subtle-art-of-giving-your-programming-self-a-b
- 45/10 https://www.sourcecon.com/2-geeky-tools-to-manage-your-sourcing-tasks/

**Comment by adrcotfas** [comment]
In my opinion, 50/10, 45/15 or 45/10 are quite similar to 52/17 so I don't think I'll add them considering the fact that users can add custom session durations according to their needs.

**Comment by DonaldTsang** [comment]
@adrcotfas would like to see 50/10 in the app, everything else is secondary (52/17 is kind of awkward to execute, 57/18 makes more sense for 15-minute based timeboxes).

**Comment by adrcotfas** [comment]
@DonaldTsang Is it a huge issue for you if it's not there by default? You can save such a custom profile in the settings.

**Comment by DonaldTsang** [comment]
@adrcotfas It is merely a social preference since 50/10 ("timeboxing" instead of "pomodoro") has as much of a reference as 52/17.
