### ISSUE TITLE
FlowTime technique

### ISSUE THREAD

**Issue by DonaldTsang** [goodtime-productivity/Goodtime#167]
https://zapier.com/blog/flowtime-technique/ has presented a technique in which people can work however long they work, and depending on how long they have worked they can take differnet amount of breaks. Is it possible to make this into an app?

**Comment by adrcotfas** [comment]
This could work if you manually skip or increase the session/break time once you feel that you're done. A feature will come soon that notifies you 1 minute before the session end so you can prolong it. This would help to achieve what is described in the article, I think.

**Comment by DonaldTsang** [comment]
@adrcotfas thanks for the support regarding this idea, hope this might enhance the app.
