### ISSUE TITLE
Add the possibility to label a session

### ISSUE THREAD

**Issue by fdw** [goodtime-productivity/Goodtime#18]
Many other pomodoro apps enable the user to enter a task for each session. The main idea is that you can later check how many pomodoro sessions you spent for each task - for example, if you spent more time coding or writing documentation.

I would like a similar feature for Goodtime as an enhancement of the session counter.

**Comment by fdw** [comment]
This is related to #27

**Comment by adrcotfas** [comment]
This was implemented on the dev branch and will be released soon.
