### ISSUE TITLE
Add stats page

### ISSUE THREAD

**Issue by j6s** [goodtime-productivity/Goodtime#27]
> As a user I would like to see stats about how many timers I have completed during the past x days

A simple stats view with a line chart would go a long way for this. 
I understand that this is not essential but it would be a great addition to the experience.

IMO The best place for this would be by tapping the counter. This would take you to the stats page  where you can look at the stats and also reset the counter.

I will have a go at implementing this but it could take some time as I am not familiar with the project.

**Comment by StefanDimov** [comment]
I think a stats page is a really good idea.

I think the best place for it is in the side menu. The home screen counter is pretty good and concise atm.

The best flow for this I think should be:
- app just gets a new tab with stats in the side menu
- by default when you finish a work session it will be displayed in the stats with by #general tag or something similar
- you can set a custom tag to each work session, so you can have stats for different activities (#work, #study, #read)
- filters - day, week, month, year
- stats
- - overview - number of work sessions, average sessions per day, average work time
- - stacked area chart (work/time) -  (example reference: https://www.highcharts.com/demo/area-stacked)
- - bar chart (activity work sessions count) - (example reference: https://www.highcharts.com/demo/bar-basic)

**Comment by adrcotfas** [comment]
Statistics are in progress and will come in the next release.
