### ISSUE TITLE
Distribution on F-Droid

### ISSUE THREAD

**Issue by maxigaz** [goodtime-productivity/Goodtime#91]
Would it be possible to make Goodtime available on F-Droid?

**Comment by imacg** [comment]
I would be very interested in this as I wish to move away from Google/Play.

From what I can tell this would require either:

1. Creating separate Free and Play build flavours to separate out the Play and Firebase dependencies, the code required for donations (donation functionality could instead be implemented with a link to a webpage or something), and putting conditionals on the layouts to hide the donation and app invite functionality in the Free flavour
2. Maintaining a Free fork

@adrcotfas I am willing to do either as well as whatever needs to be done to get the app hosted on F-Droid.

**Comment by adrcotfas** [comment]
Thanks for your interest!
I'm currently rewriting the app and have this in mind but it will take some more time.

**Comment by projectextremum** [comment]
what about putting apk on releases untill then?

I did not find there the latest apk with google services removed.

**Comment by adrcotfas** [comment]
It will come with the next version.

**Comment by adrcotfas** [comment]
A version for F-Droid will come along with v2.0. A new flavor for it was already implemented.

**Comment by IzzySoft** [comment]
That's good news! Please leave a comment here when it's out so we then can get things going for the official repo!

**Comment by adrcotfas** [comment]
I guess I'll follow the guide: https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by IzzySoft** [comment]
That's fine! Looking forward to your RFP then (hint: I'm one of the maintainers there :wink:)

**Comment by adrcotfas** [comment]
@IzzySoft I assume it would be much faster for you to put this app on F-Droid. Can you please help with this? There's an "fdroid" flavor in gradle with all the pro features unlocked. I'll keep them under IAP only on Google Play.

**Comment by IzzySoft** [comment]
[Here you go](https://gitlab.com/fdroid/rfp/issues/894), @adrcotfas. But could you please ensure that with future releases, the versionName corresponds to the tag name (the tag name can have a leading "v", that's no problem – but the versionName cannot have a trailing "b". In other words: versionName must be a part of the tag name. Otherwise our update check fails. Thanks!

**Comment by adrcotfas** [comment]
@IzzySoft That was fast 👍. I'll keep that in mind.

**Comment by IzzySoft** [comment]
@adrcotfas the APK attached to the v2.0 tag seems to lack its certificates:

    ERROR: No signing certificates found in repo/com.apps.adrcotfas.goodtime_2.0.apk

Could you please fix that, so the update can reach my repo? Thanks!

**Comment by adrcotfas** [comment]
Done. Please retry.

**Comment by IzzySoft** [comment]
@adrcotfas thanks, my "update bot" will have done that when I'm coming home (and send me a report 🤣 ) I'm sure it will be OK (otherwise you'll get another update in a few hours).

**Comment by IzzySoft** [comment]
Sorry to disappoint @adrcotfas, but my updater reported the same error again:

    ERROR: No signing certificates found in goodtime_2.0.apk
    WARNING: Skipping 'goodtime_2.0.apk' with invalid signature!

And I checked: timestamp is today 4:45pm CET, so it was the new file. Can you please check again (and make sure with `apksigner verify goodtime.apk`)?

    $ apksigner verify goodtime_2.0.apk
    DOES NOT VERIFY
    ERROR: No JAR signatures

That's what the current file gives. If the prompt simply returns, it's excellent. If it just gives WARNINGs, it's OK.

**Comment by adrcotfas** [comment]
@IzzySoft This is weird. I generated the apk with `Generate Signed Bundle/APK`. I'll investigate.

**Comment by IzzySoft** [comment]
I've stumbled upon that issue several times recently, with different projects. One time a dev told me "Android Studio has that from time to time" (not literally, but along those lines). That's why I suggested running `apksigner` on the resulting APK, just to make sure. One never nows…

And no, I definitely do *NOT* blame you :smile: I'd rather suspect Google behind that, wanting to annoy devs so much that they finally leave signing to them (so bleed 3rd party stores out of apps).

<sub>*putting tin foil on my head*</sub>

**Comment by adrcotfas** [comment]
I didn't run `apksigner` but for sure made the necessary steps in Android Studio to generate a signed apk.
https://github.com/goodtime-productivity/Goodtime/releases/tag/2.0.3

**Comment by IzzySoft** [comment]
Thanks @adrcotfas – we'll find out in a few hours. Running `apksigner verify` on the APK might save some ping-pong, though 😄

**Comment by IzzySoft** [comment]
@adrcotfas sorry to disappoint you again:

    ERROR: No signing certificates found in repo/com.apps.adrcotfas.goodtime_2.0.3.apk
    WARNING: Skipping 'com.apps.adrcotfas.goodtime_2.0.3.apk' with invalid signature!

I have absolutely no ideas what goes wrong there. Had the same issue with another app as well – but other 9 apps updated successfully, so it shouldn't be at my end.

To narrow things down: what signing are you using? v1, v2, v1+v2 …? In case of v2-only, could you try v2+v1 (i.e. enabling v1 in addition)?

**Comment by adrcotfas** [comment]
I'm using v1 + v2.

**Comment by IzzySoft** [comment]
Strange. Then there should be JAR signatures. And `apksigner` understands both v1 and v2 AFAIK… Well, maybe I save us both (additional) gray hairs and disable auto-update in my repo. Shouldn't take too long until your app shows up in the official repo, hopefully.

**Comment by ElDroidge** [comment]
This is one open source app I’d really, really like to see on F-Droid. Thank you so much, folks, for coming together and making this work! Very true to the FOSS philosophy.

**Comment by IzzySoft** [comment]
So congrats now, @adrcotfas: The app is now listed on F-Droid! Though it didn't yet make it to the website (that gets synced asynchronously), it is in the index (as you can see using [my repo-browser](https://apt.izzysoft.de/fdroid/index/apk/com.apps.adrcotfas.goodtime?repo=main)) and can be found using the F-Droid app. :+1:

In other words: This issue can be closed 😃

**Comment by adrcotfas** [comment]
Great news! Thanks a lot for your support!

**Comment by IzzySoft** [comment]
Gladly, @adrcotfas – and I have removed it from my repo to avoid confusion (different signature). Should you need my repo again, simply yell 😄
