### ISSUE TITLE
Android 8.0 adaptive icon

### ISSUE THREAD

**Issue by carter-lavering** [goodtime-productivity/Goodtime#95]
I love this app! It's by far the cleanest, best-looking and best-functioning pomodoro timer I've found.

I have a little feature request: Can we update the icon to support Android 8.0's Adaptive Icons?

Details here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by adrcotfas** [comment]
Thank you!
Of course, this is planned and I'll do it when I'll have some spare time. If you want to contribute, please go ahead :).

**Comment by lokesh-krishna** [comment]
I'd like to try. Could you please share the SVG source for the present icon?

**Comment by adrcotfas** [comment]
@lokesh-krishna It will be available in the next version.

**Comment by adrcotfas** [comment]
This was implemented on the dev branch. Will be released in v2.
