### ISSUE TITLE
Increase maximum duration for work sessions

### ISSUE THREAD

**Issue by luksprog** [goodtime-productivity/Goodtime#97]
Hello.

At the moment the work session duration is capped at 60 minutes. Could it be possible to allow the user to set a higher duration? 

Unrelated, are you still working on other issues/enhancement present here?

**Comment by adrcotfas** [comment]
The whole point of pomodoro / work sessions is to focus. It's really hard to focus on a task more than one hour but I'll consider extending the max duration.
I'm currently rewriting the app and adding extra features. I'll add it to GitHub in the near future.
